from __future__ import annotations

import hashlib
import json
from typing import Any

from llm import build_llm_client
from prompts import build_fixer_messages, build_fixer_prompt_payload


def run_fixer_agent(
    *,
    code_text: str,
    repair_plan: list[dict[str, Any]],
    issues: list[dict[str, Any]],
    symbols: list[dict[str, Any]],
    context_summary: dict[str, Any],
    memory_matches: list[dict[str, Any]],
    attempt_no: int,
    last_failure: dict[str, Any] | None = None,
    selected_context: list[dict[str, Any]] | None = None,
    repo_profile: dict[str, Any] | None = None,
    options: dict[str, Any] | None = None,
    message_text: str | None = None,
    action_history: list[dict[str, Any]] | None = None,
    standards_matches: list[dict[str, Any]] | None = None,
    retry_hints: dict[str, Any] | None = None,
) -> dict[str, Any]:
    options = options or {}
    selected_context = list(selected_context or [])
    repo_profile = dict(repo_profile or {})
    action_history = list(action_history or [])
    last_failure = dict(last_failure or {})
    standards_matches = list(standards_matches or [])
    retry_hints = dict(retry_hints or {})

    llm_client = build_llm_client(options)
    if llm_client is None:
        return _failed_output(
            attempt_no=attempt_no,
            reason="llm_not_enabled_or_missing_credentials",
            detail="LLM disabled or missing credentials. Configure SENTINEL_LLM_* or request llm_enabled=true.",
            llm_trace=[],
            tool_trace=_context_tool_trace(selected_context),
            selected_context=selected_context,
            memory_hits={"cases": memory_matches, "standards": standards_matches},
            issues=issues,
            symbols=symbols,
            context_summary=context_summary,
            repair_plan=repair_plan,
            action_history=action_history,
        )

    max_action_steps = _to_int(options.get("max_action_steps"), default=3, minimum=1)
    llm_trace: list[dict[str, Any]] = []
    tool_trace = _context_tool_trace(selected_context)
    model_output: dict[str, Any] = {}
    candidate_patch = ""
    explanation = "Patch generated by LLM"
    risk_level = "medium"

    for step in range(1, max_action_steps + 1):
        prompt_payload = build_fixer_prompt_payload(
            code_text=code_text,
            message_text=message_text,
            repair_plan=repair_plan,
            issues=issues,
            symbols=symbols,
            context_summary=context_summary,
            memory_matches=memory_matches,
            standards_matches=standards_matches,
            attempt_no=attempt_no,
            selected_context=selected_context,
            last_failure=last_failure,
            repo_profile=repo_profile,
            action_history=action_history,
            retry_hints=retry_hints,
        )
        messages = build_fixer_messages(prompt_payload)
        llm_result = llm_client.create_chat_completion(
            phase="fixer_patch_generation",
            prompt_name="fixer_patch_generation",
            messages=messages,
            stream=False,
            json_mode=True,
            tool_mode="off",
        )
        if isinstance(llm_result.trace, dict):
            llm_trace.append(llm_result.trace)

        if not llm_result.ok:
            return _failed_output(
                attempt_no=attempt_no,
                reason="llm_call_failed",
                detail=llm_result.error or "LLM call failed",
                llm_trace=llm_trace,
                tool_trace=tool_trace,
                selected_context=selected_context,
                memory_hits={"cases": memory_matches, "standards": standards_matches},
                issues=issues,
                symbols=symbols,
                context_summary=context_summary,
                repair_plan=repair_plan,
                action_history=action_history,
            )

        model_output = _safe_json(llm_result.content)
        candidate_patch = str(
            model_output.get("unified_diff")
            or model_output.get("candidate_patch")
            or model_output.get("patch")
            or ""
        ).strip()
        explanation = str(model_output.get("explanation") or model_output.get("why") or "Patch generated by LLM").strip()
        risk_level = str(model_output.get("risk_level") or "medium").strip().lower() or "medium"
        if risk_level not in {"low", "medium", "high"}:
            risk_level = "medium"

        next_action = str(model_output.get("next_action") or "").strip() or "finalize_patch"
        need_more_context = bool(model_output.get("need_more_context", False))
        action_history = action_history + [
            {
                "step": step,
                "phase": "action_loop",
                "next_action": next_action,
                "need_more_context": need_more_context,
                "has_candidate_patch": bool(candidate_patch),
            }
        ]
        if need_more_context or not candidate_patch or not tool_trace:
            tool_trace.append(
                {
                    "tool_name": next_action,
                    "success": True,
                    "phase": "action_loop",
                    "step": step,
                    "selected_context_count": len(selected_context),
                }
            )

        if candidate_patch:
            break
        if not need_more_context or next_action == "finalize_patch":
            return _failed_output(
                attempt_no=attempt_no,
                reason="no_valid_patch",
                detail="LLM response does not contain unified_diff.",
                llm_trace=llm_trace,
                tool_trace=tool_trace,
                selected_context=selected_context,
                memory_hits={"cases": memory_matches, "standards": standards_matches},
                issues=issues,
                symbols=symbols,
                context_summary=context_summary,
                repair_plan=repair_plan,
                action_history=action_history,
            )
    else:
        return _failed_output(
            attempt_no=attempt_no,
            reason="action_loop_exhausted",
            detail=f"LLM did not produce valid unified_diff within {max_action_steps} steps.",
            llm_trace=llm_trace,
            tool_trace=tool_trace,
            selected_context=selected_context,
            memory_hits={"cases": memory_matches, "standards": standards_matches},
            issues=issues,
            symbols=symbols,
            context_summary=context_summary,
            repair_plan=repair_plan,
            action_history=action_history,
        )

    validation_error = _validate_patch(candidate_patch, last_failure)
    if validation_error is not None:
        return _failed_output(
            attempt_no=attempt_no,
            reason=validation_error["reason"],
            detail=validation_error["detail"],
            llm_trace=llm_trace,
            tool_trace=tool_trace,
            selected_context=selected_context,
            memory_hits={"cases": memory_matches, "standards": standards_matches},
            issues=issues,
            symbols=symbols,
            context_summary=context_summary,
            repair_plan=repair_plan,
            action_history=action_history,
        )

    strategy_used = "llm_patch_generation" if model_output.get("unified_diff") else "llm_generation"
    patch_artifact = {
        "patch_id": f"patch_attempt_{attempt_no}",
        "attempt_no": attempt_no,
        "status": "generated",
        "format": "unified_diff",
        "content": candidate_patch,
        "unified_diff": candidate_patch,
        "content_hash": _hash_text(candidate_patch),
        "explanation": explanation,
        "risk_level": risk_level,
        "target_files": _resolve_target_files(issues, model_output),
        "strategy_used": strategy_used,
        "memory_case_ids": [str(item.get("case_id")) for item in memory_matches if item.get("case_id")],
    }

    attempt = {
        "attempt_no": attempt_no,
        "patch_id": patch_artifact["patch_id"],
        "status": "generated",
        "verified_level": "L0",
        "failure_stage": None,
        "failure_reason": None,
        "failure_detail": None,
        "memory_case_ids": patch_artifact["memory_case_ids"],
    }

    action_history = action_history + [
        {
            "step": attempt_no,
            "phase": "patch_generation",
            "result": "generated",
            "patch_id": patch_artifact["patch_id"],
            "risk_level": risk_level,
            "strategy_used": strategy_used,
        }
    ]

    return {
        "ok": True,
        "patch_artifact": patch_artifact,
        "attempt": attempt,
        "llm_trace": llm_trace,
        "tool_trace": tool_trace,
        "selected_context": selected_context,
        "memory_hits": {"cases": memory_matches, "standards": standards_matches},
        "issues": issues,
        "symbols": symbols,
        "context_summary": context_summary,
        "repair_plan": repair_plan,
        "issue_graph": {},
        "planner_summary": {},
        "action_history": action_history,
    }


def _resolve_target_files(issues: list[dict[str, Any]], model_output: dict[str, Any]) -> list[str]:
    from_model = model_output.get("target_files")
    if isinstance(from_model, list):
        files = [str(item).replace("\\", "/").strip() for item in from_model if str(item).strip()]
        if files:
            return files
    for issue in issues:
        file_path = str(issue.get("file_path") or issue.get("filePath") or "").strip()
        if file_path:
            return [file_path.replace("\\", "/")]
    return ["snippet.java"]


def _validate_patch(patch: str, last_failure: dict[str, Any]) -> dict[str, str] | None:
    if not _is_valid_unified_diff(patch):
        return {"reason": "invalid_diff", "detail": "candidate patch is not a valid unified diff"}
    if not _is_meaningful_patch(patch):
        return {"reason": "no_valid_patch", "detail": "candidate patch is whitespace/no-op/comment-only"}
    previous_hash = _resolve_previous_patch_hash(last_failure)
    if previous_hash and previous_hash == _hash_text(patch):
        return {"reason": "duplicate_patch_candidate", "detail": "candidate patch duplicates previous patch"}
    return None


def _to_int(value: Any, *, default: int, minimum: int) -> int:
    try:
        resolved = int(value)
    except Exception:
        resolved = default
    return max(minimum, resolved)


def _is_valid_unified_diff(content: str) -> bool:
    lines = content.splitlines()
    if len(lines) < 3:
        return False
    return lines[0].startswith("diff --git a/") and lines[1].startswith("--- a/") and lines[2].startswith("+++ b/")


def _is_meaningful_patch(content: str) -> bool:
    for line in content.splitlines():
        if not line.startswith("+") and not line.startswith("-"):
            continue
        if line.startswith("+++") or line.startswith("---"):
            continue
        payload = line[1:].strip()
        if not payload:
            continue
        if payload.startswith("//") or payload.startswith("/*") or payload.startswith("*"):
            continue
        return True
    return False


def _resolve_previous_patch_hash(last_failure: dict[str, Any]) -> str | None:
    hash_value = str(last_failure.get("previous_patch_hash") or "").strip()
    if hash_value:
        return hash_value
    content = str(last_failure.get("previous_patch_content") or "")
    if content:
        return _hash_text(content)
    return None


def _failed_output(
    *,
    attempt_no: int,
    reason: str,
    detail: str,
    llm_trace: list[dict[str, Any]],
    tool_trace: list[dict[str, Any]],
    selected_context: list[dict[str, Any]],
    memory_hits: dict[str, Any],
    issues: list[dict[str, Any]],
    symbols: list[dict[str, Any]],
    context_summary: dict[str, Any],
    repair_plan: list[dict[str, Any]],
    action_history: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "ok": False,
        "patch_artifact": None,
        "attempt": {
            "attempt_no": attempt_no,
            "patch_id": f"patch_attempt_{attempt_no}",
            "status": "failed",
            "verified_level": "L0",
            "failure_stage": "fixer",
            "failure_reason": reason,
            "failure_detail": detail,
            "memory_case_ids": [],
        },
        "llm_trace": llm_trace,
        "tool_trace": tool_trace,
        "selected_context": selected_context,
        "memory_hits": memory_hits,
        "issues": issues,
        "symbols": symbols,
        "context_summary": context_summary,
        "repair_plan": repair_plan,
        "issue_graph": {},
        "planner_summary": {},
        "action_history": action_history,
    }


def _context_tool_trace(selected_context: list[dict[str, Any]]) -> list[dict[str, Any]]:
    if not selected_context:
        return []
    return [
        {
            "tool_name": "context_broker",
            "selected_by": "system",
            "success": True,
            "phase": "pre_fixer",
            "selected_context_count": len(selected_context),
        }
    ]


def _safe_json(content: str) -> dict[str, Any]:
    raw = str(content or "").strip()
    if not raw:
        return {}
    try:
        parsed = json.loads(raw)
        return parsed if isinstance(parsed, dict) else {}
    except Exception:
        return {}


def _hash_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8", errors="ignore")).hexdigest()
